### ISSUE TITLE
survey-text required bug

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#646] opened 2019-07-27 11:46 UTC
fix space between autofocus and required property.

**Comment by SaoirseConnorDesai** [comment] 2020-08-05 06:02
I have the latest version of jsPsych but the required still isn't working for the survey-text plugin.

**Comment by becky-gilbert** [comment] 2020-10-11 21:24
@jodeleeuw I can't reproduce this - the required parameter seems to work fine, both when the question has one row (`input type="text"`) and multiple rows (`textarea`). Maybe this was fixed at some point but the issue was never closed? I did look through the commit history for the survey-text plugin hoping to find the commit that fixed this, but unfortunately I didn't see the bug in the file history.

**Comment by jodeleeuw** [comment] 2020-10-12 20:45
You're right it does look fixed. It's odd because if I look at the repo in July 2019 when I posted this it looks like it would have been fixed at that point, too.

**Comment by becky-gilbert** [comment] 2020-10-12 22:13
@jodeleeuw I just went back through the file history to where the required parameter was first added. I couldn't find this bug introduced anywhere, assuming the problem was a missing space before or after the required attribute. Should I close this or do more investigating?

**Comment by jodeleeuw** [comment] 2020-10-12 22:29
I'm stumped! Let's just close it and hope it was me seeing ghosts 👻

**Closed** 2020-10-12 22:38 UTC
