### ISSUE TITLE
Image preloading doesn't work when file name has spaces?

### ISSUE THREAD

**Issue by becky-gilbert** [jspsych/jsPsych#1965] opened 2021-07-03 16:58 UTC
I just ran into this problem, not sure if it's reproducible or if it is also true for audio and video files. It looks like the spaces are being replaced with %20 in the file name, which then produces a 404 because there's no file with that exact match. Might need to use something like `unescape` or `encodeURI`?

**Comment by jodeleeuw** [comment] 2021-11-27 19:50
I just made a simple demo test case for this that looks like this:

```js
    const jsPsych = initJsPsych();

    const timeline = [
      {
        type: jsPsychPreload,
        images: 'img/happy face 1.jpg',
        post_trial_gap: 3000,
      },
      {
        type: jsPsychImageButtonResponse,
        stimulus: 'img/happy face 1.jpg',
        choices: ['ok']
      }
    ]    

    jsPsych.run(timeline);
```

Everything looks like it worked OK in this particular demo. There was one load of the img in the Network tab, it was definitely during the preload trial, and there were no failed images in the preload data.

I'm gonna close this for now, but if there's a reproducible example let's reopen and investigate further.

**Closed by jodeleeuw** 2021-11-27 19:50 UTC
Labels: bug
