### ISSUE TITLE
data-only simulation causes "Maxmum call stack size exceeded" error

### ISSUE THREAD

**Issue by toreerdmann** [jspsych/jsPsych#3313] opened 2024-06-11 16:54 UTC
Hi, I have quite a long experiment and am not able to use the "data-only" simulation mode. 

Here's the error message:

![image](https://github.com/jspsych/jsPsych/assets/10772906/64041a3b-dd87-4a5d-9625-1612db3a66c3)

Here's a minimal experiment that causes the error:

```
 <!DOCTYPE html>
  <html>
      <head>     
      <script src="https://unpkg.com/jspsych@7.3.4"></script>
      <script src="https://unpkg.com/@jspsych/plugin-html-keyboard-response@1.1.3"></script>
      </head>
      <body></body>
      <script>
      let jsPsych = initJsPsych();
      let trial = {
          timeline: [
          {
              type: jsPsychHtmlKeyboardResponse,
              stimulus: "test",
              choices: ["a"],
          }],
          repetitions: 900
      };
      jsPsych.simulate([trial]);
      </script>
</html>
```

I am happy to help fixing this, but I do not know where to start. I am guessing the simulation
would have to be run in an iterative way, that does not grow the call stack as much.

**Comment by jodeleeuw** [comment] 2024-06-11 21:13
Thanks, this is really helpful information. 

We are getting close to publishing version 8, and I suspect that this is likely fixed in version 8 due to the overhaul to the timeline implementation code. I'll work on adding a test case to verify that it is fixed.

**Comment by jodeleeuw** [comment] 2024-07-11 16:19
We've confirmed that this is no longer an issue in version 8.

**Closed by jodeleeuw** 2024-07-11 16:19 UTC
Labels: bug
