### ISSUE TITLE
categorize-animation plugin frame-time issue

### ISSUE THREAD

**Issue by nikbpetrov** [jspsych/jsPsych#1885] opened 2021-06-12 22:06 UTC
## Problem statement:

the `categorize-animation` plugin's documentation states that the `frame_time` argument defines 'How long to display each image (in milliseconds).'

However, this does not seem to be entirely true. It also seems to define a pre-image blank screen duration as well as the duration of the prompt before being allowed to give a response.

## Reproducing the error

Use the [categorize-animation.html](https://github.com/jspsych/jsPsych/blob/master/examples/jspsych-categorize-animation.html) from the [examples](https://github.com/jspsych/jsPsych/tree/master/examples) folder. On the single defined trial (named `trials`), add a `frame_time` parameter and set it to a relatively large value, say, 5000. The trial would then look like this:

```javascript
var trials = {
    type: 'categorize-animation',
    stimuli: ['img/happy_face_1.jpg', 'img/sad_face_3.jpg'],
    key_answer: 'd',
    choices: ['d', 's'],
    text_answer: 'different',
    feedback_duration: 1000,
    correct_text: "<p>Correct. The faces had %ANS% expressions.</p>",
    incorrect_text: "<p>Incorrect. The faces had %ANS% expressions.</p>",
    prompt: "<p>Press &quot;d&quot; if the faces had different emotional expressions. Press &quot;s&quot; if the faces had the same emotional expression.</p>",
    frame_time: 5000
    //render_on_canvas: false
  };
```

Optionally, add a `console.log` statement in the [jspsych-categorize-animation.js](https://github.com/jspsych/jsPsych/blob/master/plugins/jspsych-categorize-animation.js) plugin file below line 133 - just at the start of the function call in setInterval, so it looks like this:
```javascript
...
// show animation
    var animate_interval = setInterval(function() {
      console.log('Interval sequence triggered')
      if (!trial.render_on_canvas) {
        display_element.innerHTML = ''; // clear everything
      }
      animate_frame++;
...
```

What you should be able to see is that there is a 5s blank screen, then image 1, then image 2 (both for 5s each) and then no response is allowed during the prompt until 5 seconds have passed. Only after those 5 seconds is response allowed. Then the feedback should appear (feedback works as expected). Also, in the console you should see that the log statement is called 4 times (although twice is expected).

## A possible solution(-ish)
I think that the problem lies partly in the documentation and partly in the code. Perhaps the blank screen is fine to kinda prepare the user, so this just needs to be documented. However, the delay for response at the end should perhaps be fixed.

It's also ever so slightly strange to see how this setInteveral is created on this plugin -- all other timeout events are handled globally in the core module, while only this is left hanging by itself. Perhaps the above issue is a consequence of this, but I am not too sure.

Hope this helps!

**Comment by becky-gilbert** [comment] 2021-06-30 20:49
Hi @nikbpetrov, you're absolutely right, thanks for flagging this! I'll ask Josh but I don't think the initial blank screen delay before the animation is intended - if someone wants to add preparation time then that could be done with a separate trial before the categorize-animation trial. So assuming this is a bug, then I think the problem is that the start of the animation is triggered inside of `setInterval`, which means it is always delayed by the `frame_time` duration. We could fix this by showing the first animation frame immediately and simultaneously setting up the `setInterval`, to continue the animation after that.

And I agree that the use of the normal JS `setInterval` function is a little weird. I'm guessing this is just because `setInterval` isn't used by many other plugins (except the animation plugin), so perhaps there was no need to set this up in the plugin API. The real benefit of handling this globally by the core module would be to make it easier to ensure that all `setInterval`s are cleared at the end of a trial. I don't think there's a huge need for this, but at the same time, you're right that it would be more consistent with how the `setTimeout` functions work.

**Comment by jodeleeuw** [comment] 2021-09-02 18:15
I think this is now fixed with https://github.com/jspsych/jsPsych/commit/03cb835bcf10085fd81f3cd533874466b500d2e7.

@nikbpetrov there is an option for allowing a response before the animation is complete (`allow_response_before_complete`) so I didn't change how the final frame behaves. But I did change things so that the animation starts immediately in both animation plugins.

**Closed** 2021-09-02 18:15 UTC
Labels: bug, plugin-modification
