### ISSUE TITLE
Change CSS for .jspsych-content to fix (RDK doesn't work with resize plugin) and other issues.

### ISSUE THREAD

**Issue by becky-gilbert** [jspsych/jsPsych#1536] opened 2021-02-18 19:17 UTC
See recent comments in #787.

**Comment by gorkemer** [comment] 2021-02-19 03:04
Hey everyone, 

Hey @vijaymarupudi, thanks for chipping in! I'd also note that including `canvas.style.position = 'block';` shifts the canvas slightly to the right, leaving empty (display_element) space at left border. I'm attaching a photo of that here. I changed the background color of the canvas to orange to see its size. That only resolved with `canvas.style.position = 'absolute';` back in. However, as discussed, that adjustment disrupts the positioning of the canvas within the window after using resize plugin. Would there be any other solutions to achieve an appropriate canvas display without tackling this slight shift to the right issue (with position = block) or a misaligned canvas size issue(with position=absolute)?

Görkem

**Comment by vijaymarupudi** [comment] 2021-02-19 03:22
Could you provide a branch with your examples, @gorkemer? I'd love to try to debug this issue.

**Comment by gorkemer** [comment] 2021-02-19 07:34
I created one: [here](https://github.com/gorkemer/rdk_canvas_resizing/tree/canvas_position_issue). That includes the experiment that I took the photos from. It allows for _full-screen_ and _resizing_. Now it is set to `canvas.style.position = 'block';`.

**Comment by vijaymarupudi** [comment] 2021-02-22 19:09
It's `canvas.style.display` not `canvas.style.positioning` btw!

The problem is that `.jspsych-content` has a max width of `95%`.

The comment (git blame: 6d3da21a) says that it is an IE 10-11 fix, I'm not sure why exactly.

```
 .jspsych-content {
   max-width: 95%; /* this is mainly an IE 10-11 fix */
   text-align: center;
   margin: auto; /* this is for overflowing content */
 }
```

if you remove that and add display: block, it works well for me.

**Comment by vijaymarupudi** [comment] 2021-02-22 19:14
Code here: https://github.com/vijaymarupudi/rdk_canvas_resizing/tree/canvas_position_issue

**Comment by gorkemer** [comment] 2021-02-24 16:52
Thanks for the troubleshooting @vijaymarupudi! I can confirm that this solved my issue. I think this issue should be noted inside the RDK plugin. Otherwise, when the RDK plugin is used with other JsPsych plugins, to produce for example a fixation cross, the center of that trial's fixation cross and the center of the RDK is not aligned, e.g., fixation cross by the RDK shifts to the right.

**Comment by jodeleeuw** [comment] 2021-02-24 16:54
👍 We will find a general patch for this for 7.0.

**Comment by vijaymarupudi** [comment] 2021-02-24 20:36
No problem, glad to help :)

**Comment by jodeleeuw** [comment] 2023-05-27 12:44
See also #3056 for related issue with canvas plugins

**Closed** 2024-07-12 01:52 UTC
Labels: bug
