### ISSUE TITLE
jsPsych.addNodeToEndOfTimeline() bug

### ISSUE THREAD

**Issue by bjmeagher** [jspsych/jsPsych#918] opened 2020-07-26 00:58 UTC
Just noticed a bug in the code for this function on line 312 of jspsych.js (version 6.1.0). The word "undefined" is misspelled, leading to the function making a callback function a mandatory second argument.

**Comment by vijaymarupudi** [comment] 2020-07-26 00:59
Duplicate of https://github.com/jspsych/jsPsych/issues/688

**Closed by vijaymarupudi** 2020-07-26 00:59 UTC

**Comment by jodeleeuw** [comment] 2020-07-26 01:42
Thanks @bjmeagher ! We will patch this in 6.2
