### ISSUE TITLE
response_allowed_while_playing plugin doesn't seem to be working

### ISSUE THREAD

**Issue by rachelkytsui** [jspsych/jsPsych#1380] opened 2021-01-18 21:47 UTC
Hi, I am currently trying to construct an experiment where I want the participants to make button responses only after the audio is played. Using the "audio-button-response" plug-in, I've set the following parameters:

```
var fam_test_trial = {
        type: "audio-button-response",
        stimulus: jsPsych.timelineVariable('audio'),
        choices: objects,
        button_html: '<button class="jspsych-btn"><img src="img/%choice%.jpg" width = "375", height = "375"></button>',
        **response_allowed_while_playing: false,**
        response_ends_trial: true,
        trial_duration: 7000,
        post_trial_gap: 300
}
```

However, even if response_allowed_while_playing has been set to false, I was still able to make a button response before the audio finished playing. 

How could I make sure a response can be made only after the audio is done, but at the same time allow the response to end the trial (after the audio has been played)? Thank you.

**Comment by jodeleeuw** [comment] 2021-01-18 22:05
Hi @rachelkytsui,

Just a quick verification: are you using jsPsych 6.2? This feature was added in 6.2, so if you happen to be using an earlier version you'll need to get the latest code before this works.

**Comment by rachelkytsui** [comment] 2021-01-18 22:07
Hi @jodeleeuw, thank you for letting back to me! Yes, I am using version 6.2.0.

**Comment by jodeleeuw** [comment] 2021-01-18 22:09
Thanks! I'll look into it and see if I can reproduce the issue.

**Comment by jodeleeuw** [comment] 2021-01-18 22:22
@rachelkytsui so far I haven't been able to replicate the problem. Here's a demo on cognition.run that shows the correct behavior:

https://4urketr702.cognition.run/

I used similar parameters to your trial, though I didn't use timeline variables or images as the buttons:

```js
var trial = {
  type: 'audio-button-response',
  stimulus: 'brainstorm-or-green-needle.mp3',
  choices: ['A', 'B'],
  response_allowed_while_playing: false,
  response_ends_trial: true,
  trial_duration: 7000,
  post_trial_gap: 300
}
```

Can you see if using the trial definition above fixes the issue? That would narrow it down to some kind of bizarre interaction with timeline variables and/or custom HTML buttons.

**Comment by rachelkytsui** [comment] 2021-01-18 22:41
@jodeleeuw It seems to be a problem with the custom HTML buttons. The above code works (i.e., not defining an image button) such that no response is allowed before the audio is done. But once I defined the button_html parameter, it's not the same anymore -- response are possible before the audio finishes.

**Comment by becky-gilbert** [comment] 2021-01-19 02:49
I'm guessing this has to do with how the plugin code is finding the button on the page in order to hide/disable it. I'll fix it on the master branch and then it'll be fixed in the next release. Sorry about this @rachelkytsui and thanks for reporting it!

**Comment by rachelkytsui** [comment] 2021-01-19 19:20
@becky-gilbert @jodeleeuw Thank you so much for the response! What would be the best way to get this to work in the current 6.2.0 version?

**Comment by jodeleeuw** [comment] 2021-01-19 20:39
I think we can patch this pretty quickly and then you can use the patched plugin before we release 6.3. Becky's diagnosis of the problem is exactly right. 

@becky-gilbert are you already working on this, or should I take care of it? I'm happy to do it. Just don't want to duplicate efforts!

**Comment by becky-gilbert** [comment] 2021-01-19 20:54
@jodeleeuw I'm not working on this now so it'd be great if you could do it! Otherwise I'll have time later today or tomorrow.

**Closed** 2021-01-19 22:00 UTC
Labels: bug

**Comment by jodeleeuw** [comment] 2021-01-19 22:02
@rachelkytsui this is now fixed! You can grab [the latest code for the plugin](https://github.com/jspsych/jsPsych/blob/master/plugins/jspsych-audio-button-response.js) and swap it into your copy of 6.2.

**Comment by rachelkytsui** [comment] 2021-01-19 22:36
@jodeleeuw It works! Thanks you so much!
