### ISSUE TITLE
Documentation of (at least) same-different-html appears out of date.

### ISSUE THREAD

**Issue by dschreij** [jspsych/jsPsych#755] opened 2020-06-12 12:01 UTC
I was trying to get the `same-different-html` plugin to work following https://www.jspsych.org/plugins/jspsych-same-different-html/, but there appear to be a lot of inconsistencies:

- https://www.jspsych.org/plugins/jspsych-same-different-html/#basic-example: The plugin is initialized as `same-different` in the example, but this needs to be `same-different-html`.
- https://www.jspsych.org/plugins/jspsych-same-different-html/#parameters: The timing parameters according to the docs are `timing_first_stim`, `timing_gap`, `timing_second_stim`, but these in reality are `first_stim_duration`, `gap_duration`, `second_stim_duration`. Additionally, passing `null` to second_stim_duration doesn't cause the stimulus to remain onscreen untill a keypress, but just uses the default timing.

**Comment by jodeleeuw** [comment] 2020-06-12 13:31
Thanks for flagging this. We'll get it updated!

**Comment by becky-gilbert** [comment] 2020-10-11 17:22
@dschreij thanks very much for pointing this out! I'm updating the docs now, and the live site will be updated when v6.2 is released, if not sooner.

@jodeleeuw the default values for `first_stim_duration` and `second_stim_duration` in the same-different-html plugin are 1000 ms. As @dschreij points out, the docs say that it's possible to set these parameters to `null`, and that that should cause the stim to be shown until any key is pressed. The reason that this doesn't work is because [jsPsych checks if any trial parameter values are `null`](https://github.com/jspsych/jsPsych/blob/66ca55478e42b606b30d7c96d391d112c980e7e1/jspsych.js#L940), and if so, assigns the default value (in this case, 1000 ms). 

One option is to use `null` as the default value for `first_stim_duration` and `second_stim_duration`, in which case passing any other value should work fine. This is the same way that it works in other plugins, where there are parameters that default to null (e.g. `stimulus_duration`, `trial_duration`).

Another option is to allow `null` as a non-default parameter value, which would mean changing the `setDefaultValues` function in jspsych.js. I'm not sure if that change could potentially cause undesired behavior in other plugins, and if there are tests in place to catch that. Happy to go for this option and do the necessary tests etc., but wanted to see what your preference was first.

**Comment by becky-gilbert** [comment] 2020-10-20 23:28
@jodeleeuw per our conversation, I won't modify the `setDefaultValues` function in jspsych.js. Instead I'm going to switch the default values for these parameters from 1000 ms to null, and check that this fixes the problem. If so, I'll merge and close this issue.

**Closed** 2020-10-20 23:53 UTC
Labels: documentation

**Comment by Rick-C-137** [comment] 2022-07-05 18:56
I'm trying to upgrade to 7.2.3 and finding that, again, the `second_stim_duration` parameter doesn't behave as expected. In my code, I would like no time-out on the second stimulus. If I pass `null`, as instructed in the documentation, the argument gets ignored (which I confirmed by dropping a debugger in the source file). Passing a numeric <=0 works, however. (Note that this means that if someone for some reason wants to set the second stimulus duration to precisely zero, it will not behave as expected.)
